baseURL      = "https://example.com/"
languageCode = "en-us"
title        = "Example Site"
copyright    = "Example Person"

# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage = false

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 3

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
