[en]
    languageName = "English"
    title        = "Example Site"
    weight       = 1
    [en.params.sidebar]
        subtitle = "Example description"

[zh]
    languageName = "简体中文"
    title        = "演示站点"
    weight       = 2
    [zh.params.sidebar]
        subtitle = "演示说明"

[zh-hant-tw]
    languageName = "正體中文"
    title        = "演示站點"
    weight       = 3
    [zh-hant-tw.params.sidebar]
        subtitle = "演示說明"

[ja]
    languageName = "日本語"
    title        = "サンプルサイト"
    weight       = 4
    [ja.params.sidebar]
        subtitle = "サンプル説明"

[ar]
    languageName      = "عربي"
    languagedirection = "rtl"
    title             = "موقع تجريبي"
    weight            = 5
    [ar.params.sidebar]
        subtitle = "وصف تجريبي"
