[goldmark]
    [goldmark.extensions]
        [goldmark.extensions.passthrough]
            enable = true

            [goldmark.extensions.passthrough.delimiters]
                block  = [["\\[", "\\]"], ["$$", "$$"]]
                inline = [["\\(", "\\)"]]

    [goldmark.renderer]
        ## Set to true if you have HTML content inside Markdown
        unsafe = true

[tableOfContents]
    endLevel   = 4
    ordered    = true
    startLevel = 2

[highlight]
    noClasses          = false
    codeFences         = true
    guessSyntax        = true
    lineNoStart        = 1
    lineNos            = true
    lineNumbersInTable = true
    tabWidth           = 4
