[build]
    publish = "exampleSite/public"

[build.environment]
    HUGO_VERSION = "0.152.2"
    HUGO_THEME = "repo"

[context.production]
    command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${URL}"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

        [plugins.inputs]
            # If it should show more verbose logs (optional, default = true)
            debug = true
            # Relative path to source directory in case you use Hugo's "--s" option
            srcdir = "exampleSite"
