[build]
    publish = "exampleSite/public"
    command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
    HUGO_VERSION = "0.74.3"
    HUGO_THEME = "repo"
    HUGO_BASEURL = "$DEPLOY_PRIME_URL"