baseurl: https://stack.jimmycai.com/demo/
languageCode: en-us
paginate: 3

# Note: This title is overridden by the title in i18n config file
title: Hugo Theme Stack Starter

theme: hugo-theme-stack

DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

services:
  disqus:
    shortname: hugo-theme-stack
  # GA Tracking ID
  googleAnalytics:
    id:

publishDir: ../public/demo
