mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true
favicon = "img/favicon.png"

[footer]
since = 2020

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "üç•"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

[sidebar.avatar]
enabled = true
local = true
src = "img/logo.jpg"

[article]
math = false
toc = true
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[comments]
enabled = true
provider = "disqus"

[comments.disqusjs]

[comments.utterances]
issueTerm = "pathname"

[comments.remark42]

[comments.vssue]
autoCreateIssue = false

[comments.waline]
emoji = ["https://unpkg.com/@waline/emojis@1.0.1/weibo"]
requiredMeta = ["name", "email", "url"]

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]

[comments.cusdis]

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true